{application,vernemq_dev,
             [{description,"VerneMQ development dependencies"},
              {vsn,"1.1.0"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {env,[]},
              {licenses,["Apache License 2.0"]},
              {modules,[auth_on_publish_hook,auth_on_publish_m5_hook,
                        auth_on_register_hook,auth_on_register_m5_hook,
                        auth_on_subscribe_hook,auth_on_subscribe_m5_hook,
                        on_auth_m5_hook,on_client_gone_hook,
                        on_client_offline_hook,on_client_wakeup_hook,
                        on_config_change_hook,on_deliver_hook,
                        on_deliver_m5_hook,on_message_drop_hook,
                        on_offline_message_hook,on_publish_hook,
                        on_publish_m5_hook,on_register_hook,
                        on_register_m5_hook,on_session_expired_hook,
                        on_subscribe_hook,on_subscribe_m5_hook,
                        on_topic_unsubscribed_hook,on_unsubscribe_hook,
                        on_unsubscribe_m5_hook,vernemq_dev_api]}]}.
